spring.application.name=Replaytool
server.port=9090
openai.api.key= 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